### ISSUE TITLE
Bug `./src/PgManyToManyRelationPlugin.js` is missing from dist

### ISSUE THREAD

**Issue by ivawzh** [graphile-contrib/pg-many-to-many#4]
Got error message

```bash
Error: Cannot find module './src/PgManyToManyRelationPlugin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at PgManyToManyPlugin (~/repo/node_modules/@graphile-contrib/pg-many-to-many/index.js:35:3)
    at Object.exports.getBuilder (~/repo/node_modules/graphile-build/node8plus/index.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

Package.json here 
```json 
{
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "@graphile-contrib/pg-many-to-many": "^1.0.0-beta.1",
    "@graphile-contrib/pg-simplify-inflector": "^3.0.0",
    "express": "^4.16.4",
    "postgraphile": "^4.2.0"
  }
}
```

Index.js here 
```js 
const express = require("express")
const { postgraphile } = require("postgraphile")
const PgManyToManyPlugin = require("@graphile-contrib/pg-many-to-many")
const PgSimplifyInflectorPlugin = require("@graphile-contrib/pg-simplify-inflector")


const app = express()

app.use(
  postgraphile(process.env.DATABASE_URL || 'postgres:///whatever_development', 'public', {
    appendPlugins: [PgManyToManyPlugin],
    graphiql: true,
    watchPg: true,
    dynamicJson: true,
    classicIds: false,
    disableDefaultMutations: true,
    enhanceGraphiql: true,
  })
)

app.listen(5000)
```

And from node modules, I can see the `/src` folder is missing. 
![image](https://user-images.githubusercontent.com/4622799/50267933-13bbab00-047d-11e9-913f-0230208d188e.png)

**Comment by mattbretl** [comment]
:flushed: 

Thanks for reporting. Fixed in beta.2.
