### ISSUE TITLE
Does pg-many-to-many require 4.1.0, or 4.1.0 or later?

### ISSUE THREAD

**Issue by seandavi** [graphile-contrib/pg-many-to-many#7]
Just asking.... 

I'm using 4.4.0-beta.3 of postgraphile:

```
Error: Plugin @graphile-contrib/pg-many-to-many@1.0.0-beta.4 requires graphile-build-pg@^4.1.0 (current version: 4.4.0-beta.3)
    at depends (/Users/sdavis2/Documents/git/omicidx-graphql/node_modules/@graphile-contrib/pg-many-to-many/index.js:17:15)
    at PgManyToManyPlugin.builder.hook.build (/Users/sdavis2/Documents/git/omicidx-graphql/node_modules/@graphile-contrib/pg-many-to-many/index.js:26:5)
```

**Comment by benjie** [comment]
Upgrade postgraphile (and by extension graphile-build-pg) to the latest @next - it wasn't respecting pre-releases before. Fixed in https://github.com/graphile/graphile-engine/pull/419
