### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by localredhead** [graphile-contrib/pg-many-to-many#8]
Hello, I see this error when using postgraphile as a library and including pg-many-to-many

I have `"@graphile-contrib/pg-many-to-many": "^1.0.0-beta.4",` and 
`"postgraphile": "^4.4.0-beta.13",`

```sh
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/@graphile-contrib/pg-many-to-many/src/PgManyToManyRelationPlugin.js:1:84)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by benjie** [comment]
Can confirm: debug is missing from the dependencies. As a temporary workaround, installing debug in your project directly should fix it.

**Comment by mattbretl** [comment]
Fixed in beta.5. I replaced the use of `debug` (which was surely copied from one of the core plugins) with throwing an error, because if that checks ever fails, I'd want to know about it.

**Comment by localredhead** [comment]
Thanks for the quick response!
